permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up cachix
        uses: cachix/cachix-action@v14
        with:
          name: jcdickinson
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: "nix build .#poe2filter"
      - name: Tar
        run: |
          cp result/bin/poe2filter poe2filter
          tar -czf "poe2filter-linux-musl-x86_64.tar.gz" poe2filter LICENSE
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: poe2filter-linux-musl-x86_64.tar.gz
